server:
  port: 8081

spring:
  application:
    name: Ventas
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ventas_bd
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html